### ISSUE TITLE
Error #998: Unknown Error

### ISSUE THREAD

**Issue by Zyrille** [YellowPhoenix18/RealisticWorldGenerator#10]
My server has suddenly started crashing every start up, I've identified RWG to be the cause. However the error bit that's showing up on my logs aren't really very helpful. Has anyone encountered this problem?

`19.10 11:24:16 [Server] INFO RealisticWorldGenerator with Version 3.5.5 couln't be loaded 19.10 11:24:16 [Server] INFO Error #998 : Unknown Error! 19.10 11:24:16 [Server] INFO For more information: https://license.yellowphoenix18.de 19.10 11:24:16 [Server] INFO License-Key: c9ee6a5748a3abfcc138f9abd98435cf`

RWG Version: 3.5.5
MC Version: 1.12

**Comment by YellowPhoenix18** [comment]
Caused by an to old version.

Please update to the newest version

**Comment by Zyrille** [comment]
Alright, that's what I downloaded because it's the only one labeled for 1.12+ as seen from this screenshot: http://i.zyrl.space/0l0Qax.png can you tell me which ones from above is the latest version for 1.12?

**Comment by YellowPhoenix18** [comment]
Every Version which is assaigned with 1.8-latest is working for all Versions up from 1.8
