### ISSUE TITLE
Wiki - Website down

### ISSUE THREAD

**Issue by iMemphisXx** [YellowPhoenix18/RealisticWorldGenerator#11]
Hello,
I was trying to access the Wiki to learn more about the plugin, however, it doesn't look like it works anymore. Upon accessing https://community.yellowphoenix18.de/?page=wiki&id=2, I am returned with a 500 Internal Server Error error.

**Comment by YellowPhoenix18** [comment]
Oh, thats my bad. All my services has changed^^ Try out https://wiki.yellowphoenix18.de
