### ISSUE TITLE
Server crashes when I try and make a new RWG world...

### ISSUE THREAD

**Issue by TheKellyTV** [YellowPhoenix18/RealisticWorldGenerator#12]
Hi there. So my server crashes every time I try and make a new world with the realistic world generator plugin. My server is hosted by McProHosting. It comes with 12 core processors and 2.5GB of RAM. Do you know what could be causing the lag? 

The plugins I use are:
Plugins (14): CoreProtect, AutoSaveWorld, WorldEdit, MCLink, Essentials, EssentialsChat, PermissionsEx, EssentialsAntiBuild, AdvancedBan, Realistic_World, WorldGuard, Multiverse-Core, DiscordSRV, EssentialsProtect

**Comment by YellowPhoenix18** [comment]
Do you have any logs? Without any log it is not possible to locate the problem

**Comment by TheKellyTV** [comment]
I'll have to generate a new log since it will crash again anyways and re-add the plugin. I removed it until we got this covered. 😛

**Comment by TheKellyTV** [comment]
Here you go: https://pastebin.com/Gx9Ykevf

**Comment by YellowPhoenix18** [comment]
Seems, that youre using craftbukkit. Please switch to Spigot, that is working much better. Also an problem is, that many of your plugins are posting errors, please fix that, to make sure, that they do not affect RWG.

Also Important: The 12cores are not 12cores, theyre given to every single minecraft-server on that hosting-machine. In the end youre having round about 2cores, you can use. For my plugin I recommend 8 dedicated cores with high frequenzy!

**Comment by YellowPhoenix18** [comment]
Seems to be resolved
