### ISSUE TITLE
Incomplete Generation

### ISSUE THREAD

**Issue by JTGgamer** [YellowPhoenix18/RealisticWorldGenerator#14]
When generating a world, it becomes incomplete and reverts back to the vanilla world. the server has 6 gigs of memory so its enough easily.

**Comment by YellowPhoenix18** [comment]
Is the plugin still loaded? As long, as RWG is not loaded, the g

**Comment by JTGgamer** [comment]
yep

**Comment by YellowPhoenix18** [comment]
Than please send me the log, seems to me, that you`re currently the only one, who has this problem

**Comment by YellowPhoenix18** [comment]
In your log-directory?!

**Comment by JTGgamer** [comment]
How should i send it? Through here?

**Comment by YellowPhoenix18** [comment]
There some nice pages like https://pastebin.com or https://hastebin.com. Please post it there and send it here

**Comment by JTGgamer** [comment]
but they are blank zip files

**Comment by YellowPhoenix18** [comment]
There should be a log named latest.log. This shouldnt be a zip-file. Next time: If you have such a problem, where you dont know, what youre doing: PM me on Spigot. This issue-system is just for Issues and not planned for conversations

**Comment by YellowPhoenix18** [comment]
Seems for me normal. Have you tried to generate a second world? Maybe pregenerate to prevent auch problems?

**Comment by JTGgamer** [comment]
ill try that for when i release from/to beta.

**Comment by YellowPhoenix18** [comment]
Ok, i set it to resolved than. If there is a problem agsin, just reopen 😅
