### ISSUE TITLE
[Question] - Biome size

### ISSUE THREAD

**Issue by Blackdigits** [YellowPhoenix18/RealisticWorldGenerator#15]
Hi there, I am having a world generated, and there's too much plains or the lands are too mountain-y. How do I make it so that the biome size isn't so big? So there's more variety in biomes?

**Comment by YellowPhoenix18** [comment]
You can use the WorldPresets with /rwg setWorldType :)

This WorldTypes are Presets, which modify the y-height.

For the plains: This are generated by Minecraft itself, so just try an new world :)

For more infos: https://wiki.yellowphoenix18.de
