### ISSUE TITLE
[Issue] Generation Problems

### ISSUE THREAD

**Issue by JTGgamer** [YellowPhoenix18/RealisticWorldGenerator#17]
![2018-06-24_02 46 11](https://user-images.githubusercontent.com/27565081/41820503-2ed3167a-7766-11e8-8904-f7d6fbfb8f66.png)
Whenever i load a world with the realistic world generator it has holes and sometimes entire regions of vanilla gen. i have enough ram (6 gigs) and no errors in my console.

**Comment by YellowPhoenix18** [comment]
Seems to be an Problem with Bukkit. I will have a look at that and will try to fix it in future

**Comment by YellowPhoenix18** [comment]
Please send me some Infos to your server and an Timings-Report, please

**Comment by JTGgamer** [comment]
thanks, and i'm using spigot

**Comment by JTGgamer** [comment]
timing-report?
what information do u need?

**Comment by YellowPhoenix18** [comment]
Do a Timings-Report, with /timings on, than let your server work like all day and after 15mins or so, you enter /timings report. This will create an Report to the Server-Load and all Plugins, which have an heavy load, the geberated link is the link, you have to send me here. Als important to know would be the hardware of the server, like CPU, RAM and Disk. Also important: MinecraftServer, vServer or dedicaded Server

**Comment by YellowPhoenix18** [comment]
Seems like everything is fine. Was the plugin loaded, while the vanilla chunks were created? 
Also nice to know would be the WorldManagement. Is it Multiverse or Multiworld?

**Comment by JTGgamer** [comment]
multiverse and the plugin is always loaded

**Comment by YellowPhoenix18** [comment]
Maybe you try Multiworld, this is the plugin, where I am teating on. 
And yeah, the plugin is always loaded, but my idea is, that the problem is by Multiverse, when it is not loaded, the world gets mistakes.
But I can not guarantee that.

**Comment by JTGgamer** [comment]
ok, but i have loaded the world and created a spawn for release to open beta, i can't make a new spawn but there are holes in gen and idk what 2 do

**Comment by YellowPhoenix18** [comment]
The holes cant be fixed, because theire already saved to file. So this is an really big issue, which is caused by Multiverse and thats not good :/
