### ISSUE TITLE
World Gen Bug #2

### ISSUE THREAD

**Issue by fernandopal** [YellowPhoenix18/RealisticWorldGenerator#3]
RWG version: 2.8.4
MC Version: 1.11.2

http://subefotos.com/ver/?394e54181c92e0fdb3634e003aed3c6co.jpg

**Comment by YellowPhoenix18** [comment]
Have you removed the plugin while it was generating?

**Comment by fernandopal** [comment]
No, i change the world and the plugin to pther server (same config and same version)

**Comment by YellowPhoenix18** [comment]
Do you also renamed the world? Maybe forgotton to change also the per-world-configs-folder?

**Comment by YellowPhoenix18** [comment]
Seems to be fixed
