### ISSUE TITLE
No Strongholds or villages

### ISSUE THREAD

**Issue by NAHVUS** [YellowPhoenix18/RealisticWorldGenerator#4]
There seem to be no villages and no strongholds. Is there a way that these were disabled, or I can find one to verify that they are actually in the world?

**Comment by YellowPhoenix18** [comment]
RWG doesnt support villages and mineshafts.
Structures that are currently supported are:
- Pyramids
- JungleTemples
- Desert-Reservouirs
- JungleBuilding
