### ISSUE TITLE
[RWG] Not supported on this verison of minecraft

### ISSUE THREAD

**Issue by hoffarthaustin** [YellowPhoenix18/RealisticWorldGenerator#6]
On my server everytime on join OP or not you can see the RWG plugin state that your not using the correct MC version with the plugin version which is understandable because I use the ViaVersion plugin. But I dont want this message to be displayed to regular users, OP's fine.

**Comment by YellowPhoenix18** [comment]
This message should only be displayed to OPs and this message only display if you use the wrong version. If you have an 1.8-Server you have to use an 1.8-Version of my plugin, if you do this, there will be.no issue, also with ViaVersion.
