### ISSUE TITLE
The server stops responding

### ISSUE THREAD

**Issue by fernandopal** [YellowPhoenix18/RealisticWorldGenerator#9]
Plugin version: RWG2 [1.8-latest] 3.6.3
Spigot version: 1.10
Server ram: 5GB
VPS cpu: INTEL XEON x8 Cores (x4 2.6ghz x4 3.3ghz)

https://pastebin.com/Lr5jehxf

**Comment by YellowPhoenix18** [comment]
Seems to be an overload of your CPU, maybd try an timings-report or test another WorldManager like Multiworld, that can handle better big loads of Data
